#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : CNTK
Version  : 1.7.2
Release  : 3
URL      : https://github.com/Microsoft/CNTK/archive/v1.7.2.tar.gz
Source0  : https://github.com/Microsoft/CNTK/archive/v1.7.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSL-1.0
Requires: CNTK-bin
BuildRequires : mpich-dev
BuildRequires : openblas
BuildRequires : opencv-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools
BuildRequires : zlib-dev
Patch1: build.patch

%description
1) To train Kaldi GMM systems
run_ihm.sh
run_mdm.sh
run_sdm.sh
2) To train Kaldi DNN systems
run_dnn.sh

%package bin
Summary: bin components for the CNTK package.
Group: Binaries

%description bin
bin components for the CNTK package.


%package dev
Summary: dev components for the CNTK package.
Group: Development
Requires: CNTK-bin
Provides: CNTK-devel

%description dev
dev components for the CNTK package.


%prep
%setup -q -n CNTK-1.7.2
%patch1 -p1

%build
export LANG=C
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
%configure --disable-static --with-openblas=/usr \
--with-opencv
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install
## make_install_append content
chmod a+x %{buildroot}/usr/bin/*
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cntk
/usr/bin/cntk.core.bs
/usr/bin/cppevalclient
/usr/bin/v2librarytests

%files dev
%defattr(-,root,root,-)
/usr/lib64/*.so
